import { ArrowLeft, CalendarPlus, CheckCircle2, Share2 } from 'lucide-react';
import Status from '../components/Status';
import { cn, dateText, playerStatus, timeText } from '../lib/format';

export default function PlayerStatus({ match, registration, back, retry, refresh, toast }) {
  const confirmed = registration.status === 'CONFIRMED'; const submitted = registration.payment?.status === 'SUBMITTED'; const rejected = registration.status === 'REJECTED'; const waitlisted = registration.status === 'WAITLISTED';
  const content = confirmed ? ['YOU’RE IN!', 'Your payment is confirmed. Arrive 15 minutes early and bring your game.'] : submitted ? ['PAYMENT IN REVIEW', 'We have your screenshot. The organiser will confirm your spot shortly.'] : waitlisted ? ['YOU’RE WAITLISTED', 'The squad is full. We’ll notify you if a spot opens up.'] : ['PAYMENT NEEDS ATTENTION', registration.payment?.rejection_reason || 'Please submit a new payment screenshot.'];
  const share = async () => { if (navigator.share) await navigator.share({ title: match.name, url: window.location.href }); else { await navigator.clipboard?.writeText(window.location.href); toast('Match link copied'); } };
  const calendar = () => { const start = `${match.date.replaceAll('-', '')}T${match.start_time.replaceAll(':', '')}00`; const end = `${match.date.replaceAll('-', '')}T${match.end_time.replaceAll(':', '')}00`; const file = new Blob([`BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nDTSTART;TZID=Asia/Kolkata:${start}\nDTEND;TZID=Asia/Kolkata:${end}\nSUMMARY:${match.name}\nLOCATION:${match.venue}\nEND:VEVENT\nEND:VCALENDAR`], { type: 'text/calendar' }); const a = document.createElement('a'); a.href = URL.createObjectURL(file); a.download = 'stranger-club-match.ics'; a.click(); };
  return <section className="status-page"><button className="back" onClick={back}><ArrowLeft /> MATCH DETAILS</button><div className={cn('status-icon', confirmed && 'success', rejected && 'danger')}><CheckCircle2 /></div><p className="eyebrow">{dateText(match.date)}</p><h1>{content[0]}</h1><p>{content[1]}</p><div className="ticket"><div><b>{match.name}</b><span>{timeText(match.start_time)} · {match.venue}</span></div><Status status={playerStatus(registration)} /><footer><small>PAYMENT</small><strong>{confirmed ? `₹${registration.payment?.amount}` : submitted ? 'VERIFYING' : waitlisted ? 'WAITLISTED' : 'REUPLOAD'}</strong></footer></div>{confirmed && <button className="primary-button" onClick={calendar}><CalendarPlus /> ADD TO CALENDAR</button>}{submitted && <button className="primary-button" onClick={refresh}>REFRESH STATUS</button>}{rejected && <button className="primary-button" onClick={retry}>UPLOAD NEW PROOF</button>}<button className="ghost-button" onClick={share}><Share2 /> SHARE MATCH</button></section>;
}
