from __future__ import annotations

from pathlib import Path
from typing import Protocol


class Storage(Protocol):
    """Binary object storage for payment proofs and QR images. Keys are
    always opaque (uuid4-generated by the caller) — never derived from user
    input — so no implementation needs to sanitise a path itself.
    """
    def put(self, key: str, data: bytes) -> None: ...
    def path_for(self, key: str) -> Path | None: ...
    def delete(self, key: str) -> None: ...


def _guard_key(key: str) -> str:
    """Defence in depth: every real key is a uuid4 hex string produced by
    this codebase, never user input, but a bug elsewhere should not be able
    to turn this layer into a path-traversal primitive."""
    if not key or "/" in key or "\\" in key or ".." in key:
        raise ValueError(f"Unsafe storage key: {key!r}")
    return key


class LocalFilesystemStorage:
    """Storage backend for local dev and the current single-container
    deployment. Swappable for an S3-compatible backend later without any
    calling code changing (see S3Storage)."""

    def __init__(self, root: Path):
        self.root = root
        self.root.mkdir(parents=True, exist_ok=True)

    def put(self, key: str, data: bytes) -> None:
        (self.root / _guard_key(key)).write_bytes(data)

    def path_for(self, key: str) -> Path | None:
        path = self.root / _guard_key(key)
        return path if path.is_file() else None

    def delete(self, key: str) -> None:
        (self.root / _guard_key(key)).unlink(missing_ok=True)


class S3Storage:
    """Not implemented. Documents the swap point for a future S3-compatible
    backend: same three-method interface as LocalFilesystemStorage, so no
    application code above this layer would need to change when it lands."""

    def __init__(self, bucket: str, prefix: str = ""):
        raise NotImplementedError("S3Storage is not implemented yet; use LocalFilesystemStorage")
