from __future__ import annotations

import mimetypes
from pathlib import Path
from typing import Protocol


class StorageUnavailableError(RuntimeError):
    """Raised after a storage backend's bounded retries are exhausted (or
    for a simulated failure in tests). Routers translate this into a clean
    503 — never a raw backend error reaches the client."""


class Storage(Protocol):
    """Binary object storage for payment proofs and QR images. Keys are
    always opaque (uuid4-generated by the caller) — never derived from user
    input — so no implementation needs to sanitise a path itself.

    Deliberately capability-focused and deliberately has NO delete method:
    payment-proof evidence is append-only, and normal application code paths
    must never be able to remove an accepted proof, even by accident. Any
    exceptional/manual cleanup (see scripts/reconcile_storage.py) uses a
    separate, more-privileged interface and credential — never this one.
    """
    def put(self, key: str, data: bytes, content_type: str) -> None: ...
    def get(self, key: str) -> tuple[bytes, str] | None: ...
    def exists(self, key: str) -> bool: ...
    def presigned_url(self, key: str, *, expires_in: int) -> str | None: ...


def _guard_key(key: str) -> str:
    """Defence in depth: every real key is a uuid4 hex string produced by
    this codebase, never user input, but a bug elsewhere should not be able
    to turn this layer into a path-traversal primitive."""
    if not key or "/" in key or "\\" in key or ".." in key:
        raise ValueError(f"Unsafe storage key: {key!r}")
    return key


class LocalFilesystemStorage:
    """Storage backend for local dev and testing. No delete method — matches
    production's Storage protocol exactly; a developer wanting to clear
    local uploads does so directly on the filesystem, outside the app."""

    def __init__(self, root: Path):
        self.root = root
        self.root.mkdir(parents=True, exist_ok=True)

    def put(self, key: str, data: bytes, content_type: str) -> None:
        (self.root / _guard_key(key)).write_bytes(data)

    def get(self, key: str) -> tuple[bytes, str] | None:
        path = self.root / _guard_key(key)
        if not path.is_file():
            return None
        content_type = mimetypes.guess_type(key)[0] or "application/octet-stream"
        return path.read_bytes(), content_type

    def exists(self, key: str) -> bool:
        return (self.root / _guard_key(key)).is_file()

    def presigned_url(self, key: str, *, expires_in: int) -> str | None:
        return None  # local dev serves bytes directly; no presigning concept applies
