import { useState } from 'react';
import { ArrowLeft, ChevronRight, LoaderCircle } from 'lucide-react';
import Field from '../components/Field';
import FormError from '../components/FormError';
import { api } from '../lib/api';

export default function Create({ back, created }) {
  const [form, setForm] = useState({ name: 'Sunday Cricket', date: '2026-08-30', start_time: '07:00', end_time: '10:00', venue: 'PlayArena, Bellandur', capacity: '22', fee: '300', registration_deadline: '2026-08-29T20:00', upi_id: 'strangerclub@upi', payee_name: 'Stranger Club' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const update = (k) => (v) => setForm({ ...form, [k]: v });
  const submit = async (e) => { e.preventDefault(); setBusy(true); try { created(await api('/admin/matches', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, capacity: +form.capacity, fee: +form.fee, registration_deadline: `${form.registration_deadline}:00` }) })); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <section className="create"><button className="back" onClick={back}><ArrowLeft /> DASHBOARD</button><div className="intro"><p className="eyebrow">NEW GAME</p><h1>SET THE STAGE.</h1><p>Make the next match shareable in a minute.</p></div><form className="form admin-form" onSubmit={submit}><Field label="MATCH NAME" value={form.name} set={update('name')} required /><div className="pair"><Field label="DATE" type="date" value={form.date} set={update('date')} required /><Field label="CAPACITY" type="number" min="2" value={form.capacity} set={update('capacity')} required /></div><div className="pair"><Field label="START" type="time" value={form.start_time} set={update('start_time')} required /><Field label="END" type="time" value={form.end_time} set={update('end_time')} required /></div><Field label="VENUE" value={form.venue} set={update('venue')} required /><div className="pair"><Field label="FEE (₹)" type="number" min="1" value={form.fee} set={update('fee')} required /><Field label="UPI ID" value={form.upi_id} set={update('upi_id')} required /></div><Field label="PAYEE NAME" value={form.payee_name} set={update('payee_name')} required /><Field label="REGISTRATION CLOSES" type="datetime-local" value={form.registration_deadline} set={update('registration_deadline')} required /><FormError>{error}</FormError><button className="primary-button" disabled={busy}>{busy ? <LoaderCircle className="spin" /> : 'CREATE & GET LINK'}<ChevronRight /></button></form></section>;
}
