import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUpRight, CalendarPlus, Check, CheckCircle2, ChevronRight, Clock3, Copy, ImagePlus, LoaderCircle, MapPin, Plus, Share2, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import './index.css';

const DEFAULT_MATCH = 'sunday-cricket-2026';
let csrfToken = '';
const api = async (path, options = {}) => { const headers = new Headers(options.headers || {}); if (csrfToken && ['POST', 'PUT', 'PATCH', 'DELETE'].includes((options.method || 'GET').toUpperCase()) && path !== '/auth/login') headers.set('X-CSRF-Token', csrfToken); const response = await fetch(`/api${path}`, { ...options, headers, credentials: 'same-origin' }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error?.message || body.detail || 'Something went wrong. Please try again.'); return body; };
const cn = (...names) => names.filter(Boolean).join(' ');
const dateText = (value) => new Intl.DateTimeFormat('en-IN', { weekday: 'short', day: 'numeric', month: 'short' }).format(new Date(`${value}T12:00:00`));
const timeText = (value) => new Intl.DateTimeFormat('en-IN', { hour: 'numeric', minute: '2-digit' }).format(new Date(`2000-01-01T${value}`));

function Brand({ light = false }) { return <a className={cn('brand', light && 'brand--light')} href={`/m/${DEFAULT_MATCH}`}><span>SC</span>STRANGER CLUB</a>; }
function playerStatus(item) { if (item?.payment?.status === 'SUBMITTED') return 'PAYMENT_SUBMITTED'; return item?.status; }
function Status({ status }) { const text = { PENDING: 'PAYMENT DUE', PAYMENT_SUBMITTED: 'IN REVIEW', CONFIRMED: 'CONFIRMED', REJECTED: 'ACTION NEEDED', WAITLISTED: 'WAITLISTED' }[status] || status; return <span className={cn('status', `status--${status?.toLowerCase()}`)}>{text}</span>; }
function Toast({ text, clear }) { useEffect(() => { if (text) { const timer = setTimeout(clear, 3000); return () => clearTimeout(timer); } }, [text, clear]); return text ? <div className="toast"><CheckCircle2 size={16} />{text}</div> : null; }
function Loading() { return <main className="loading"><Brand /><LoaderCircle className="spin" /><p>SETTING THE FIELD</p></main>; }
function ErrorPage({ message }) { return <main className="error-page"><Brand /><h1>WE CAN’T FIND<br />THIS MATCH.</h1><p>{message}</p><a className="primary-button" href={`/m/${DEFAULT_MATCH}`}>VIEW LATEST MATCH <ChevronRight size={19} /></a></main>; }
function Field({ label, value, set, ...input }) { return <label className="field"><span>{label}</span><input value={value} onChange={(e) => set(e.target.value)} {...input} /></label>; }
function FlowHeader({ step, label, back }) { return <header className="flow-header"><button onClick={back}><ArrowLeft /></button><span>{step} / 02 · {label}</span><Brand /></header>; }
function FormError({ children }) { return children && <p className="form-error">{children}</p>; }

export default function App() {
  const path = window.location.pathname;
  if (path === '/admin/login') return <AdminLogin />;
  return path.startsWith('/admin') ? <Admin /> : <Player publicId={path.match(/^\/(?:m|events)\/([^/]+)/)?.[1] || DEFAULT_MATCH} />;
}

function Player({ publicId }) {
  const [match, setMatch] = useState(); const [registration, setRegistration] = useState(); const [page, setPage] = useState('match'); const [error, setError] = useState(''); const [toast, setToast] = useState(''); const key = `sc-registration-${publicId}`;
  const load = async () => { try { setError(''); const item = await api(`/events/${publicId}`); setMatch(item); const registrationId = localStorage.getItem(key); if (registrationId) { try { const player = await api(`/registrations/${registrationId}`); setRegistration(player); if (player.status !== 'PENDING' || player.payment) setPage('status'); } catch { localStorage.removeItem(key); } } } catch (err) { setError(err.message); } };
  useEffect(() => { load(); }, [publicId]);
  useEffect(() => { const stream = new EventSource(`/api/events/${publicId}/stream`); stream.onmessage = () => load(); stream.addEventListener('summary', () => load()); return () => stream.close(); }, [publicId]);
  const save = (item) => { setRegistration(item); localStorage.setItem(key, item.public_id); };
  if (error) return <ErrorPage message={error} />;
  if (!match) return <Loading />;
  return <main className="app"><Toast text={toast} clear={() => setToast('')} />
    {page === 'match' && <Match match={match} join={() => setPage('form')} />}
    {page === 'form' && <Register match={match} back={() => setPage('match')} done={(item) => { save(item); setPage(item.status === 'WAITLISTED' ? 'status' : 'pay'); }} />}
    {page === 'pay' && <Pay match={match} registration={registration} back={() => setPage('form')} done={(item) => { save(item); setPage('status'); }} toast={setToast} />}
    {page === 'status' && <PlayerStatus match={match} registration={registration} back={() => setPage('match')} retry={() => setPage('pay')} refresh={async () => { save(await api(`/registrations/${registration.public_id}`)); setToast('Status updated'); }} toast={setToast} />}
  </main>;
}

function Match({ match, join }) {
  const available = match.available_slots; const full = available === 0; const fill = Math.round((match.confirmed_count / match.capacity) * 100);
  return <><section className="match-hero"><div className="grid" /><header className="public-header"><Brand light /><a href="/admin">ORGANIZER <ArrowUpRight size={14} /></a></header><div className="hero-copy"><p className="eyebrow lime">WEEKLY PICK-UP CRICKET</p><h1>{match.name}</h1><div className="date-lock"><b>{new Date(`${match.date}T12:00:00`).getDate()}</b><span>{new Intl.DateTimeFormat('en-IN', { month: 'short' }).format(new Date(`${match.date}T12:00:00`))}<br />2026</span></div><p><Clock3 size={17} />{timeText(match.start_time)} — {timeText(match.end_time)}</p></div><div className="field-graphic"><div><i /><i /><i /></div><b>{String(match.capacity).padStart(2, '0')}</b></div></section><section className="match-body"><p className="venue"><MapPin size={19} />{match.venue}</p><div className="facts"><div><span>GAME FEE</span><b>₹{match.fee}</b></div><div><span>STARTS</span><b>{timeText(match.start_time)}</b></div></div><div className="availability"><div><span><small>SQUAD STATUS</small><b>{full ? 'MATCH FULL' : `${available} SPOTS LEFT`}</b></span><strong>{match.confirmed_count}<i>/{match.capacity}</i></strong></div><div className="meter"><i style={{ width: `${fill}%` }} /></div><p>{match.confirmed_count} confirmed · {match.payment_submitted_count} payment pending · {match.waitlist_count} waitlisted</p></div><div className="detail"><div><CalendarPlus /><small>DATE</small><b>{dateText(match.date)}</b></div><div><MapPin /><small>VENUE</small><b>{match.venue}</b></div></div><div className="club-note"><Sparkles /><p><b>GOOD GAMES. GOOD PEOPLE.</b>Come solo. We’ll sort the teams. Please arrive 15 minutes early.</p></div></section><div className="sticky"><p>{full ? 'We’ll notify you if a spot opens' : `₹${match.fee} · takes less than a minute`}</p><button className="primary-button" onClick={join}>{full ? 'JOIN WAITLIST' : 'JOIN MATCH'}<ChevronRight /></button></div></>;
}

function Register({ match, back, done }) {
  const [form, setForm] = useState({ name: '', phone: '', email: '', preferred_position: 'NO_PREFERENCE' }); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async (e) => { e.preventDefault(); setBusy(true); try { done(await api(`/events/${match.public_id}/registrations`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) })); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <section className="flow"><FlowHeader step="01" label="YOUR DETAILS" back={back} /><div className="intro"><p className="eyebrow">SUNDAY CRICKET</p><h1>WHO’S PLAYING?</h1><p>Just the essentials. No account required.</p></div><form onSubmit={submit} className="form"><Field label="FULL NAME" placeholder="Your name" value={form.name} set={(v) => setForm({ ...form, name: v })} autoFocus required /><Field label="MOBILE NUMBER" placeholder="10-digit number" type="tel" inputMode="numeric" value={form.phone} set={(v) => setForm({ ...form, phone: v })} required /><Field label="EMAIL · OPTIONAL" placeholder="For your match confirmation" type="email" value={form.email} set={(v) => setForm({ ...form, email: v })} /><label className="field"><span>PREFERRED ROLE · OPTIONAL</span><select value={form.preferred_position} onChange={(event) => setForm({ ...form, preferred_position: event.target.value })}><option value="NO_PREFERENCE">No preference</option><option value="BATSMAN">Batsman</option><option value="BOWLER">Bowler</option><option value="ALL_ROUNDER">All-rounder</option><option value="WICKET_KEEPER">Wicket keeper</option></select></label><FormError>{error}</FormError><button className="primary-button" disabled={busy || !form.name || !form.phone}>{busy ? <LoaderCircle className="spin" /> : 'CONTINUE'}<ChevronRight /></button></form><p className="privacy"><ShieldCheck size={16} /> Your details are only used to organise this match.</p></section>;
}

function Pay({ match, registration, back, done, toast }) {
  const [file, setFile] = useState(); const [preview, setPreview] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const input = useRef(); const uri = `upi://pay?pa=${encodeURIComponent(match.upi_id)}&pn=Stranger%20Club&am=${match.fee}&cu=INR`;
  useEffect(() => { if (!file) return; const link = URL.createObjectURL(file); setPreview(link); return () => URL.revokeObjectURL(link); }, [file]);
  const upload = async () => { if (!file) return; setBusy(true); const body = new FormData(); body.append('screenshot', file); try { done(await api(`/registrations/${registration.public_id}/payment`, { method: 'POST', body })); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <section className="flow"><FlowHeader step="02" label="PAYMENT" back={back} /><div className="pay-total"><small>MATCH FEE</small><b>₹{match.fee}</b><span>Pay with any UPI app</span></div><div className="qr-panel"><p>SCAN TO PAY</p><div className="qr"><QRCodeSVG value={uri} size={166} includeMargin /></div><button className="upi" onClick={async () => { await navigator.clipboard?.writeText(match.upi_id); toast('UPI ID copied'); }}><span><small>UPI ID</small>{match.upi_id}</span><Copy size={18} /></button></div><div className="proof"><p className="eyebrow">PAYMENT PROOF</p><h2>UPLOAD YOUR SCREENSHOT</h2><p>We’ll review it shortly and confirm your spot.</p>{preview ? <div className="preview"><img src={preview} alt="Payment proof selected" /><button onClick={() => input.current.click()}>CHANGE</button></div> : <button className="upload" onClick={() => input.current.click()}><ImagePlus /><b>UPLOAD SCREENSHOT</b><span>JPEG, PNG or WEBP · max 5 MB</span></button>}<input ref={input} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => setFile(e.target.files?.[0])} />{file && <p className="ready"><Check /> Screenshot selected</p>}<FormError>{error}</FormError></div><button className="primary-button pay-submit" disabled={!file || busy} onClick={upload}>{busy ? <LoaderCircle className="spin" /> : 'SUBMIT PAYMENT PROOF'}<ChevronRight /></button></section>;
}

function PlayerStatus({ match, registration, back, retry, refresh, toast }) {
  const confirmed = registration.status === 'CONFIRMED'; const submitted = registration.payment?.status === 'SUBMITTED'; const rejected = registration.status === 'REJECTED'; const waitlisted = registration.status === 'WAITLISTED';
  const content = confirmed ? ['YOU’RE IN!', 'Your payment is confirmed. Arrive 15 minutes early and bring your game.'] : submitted ? ['PAYMENT IN REVIEW', 'We have your screenshot. The organiser will confirm your spot shortly.'] : waitlisted ? ['YOU’RE WAITLISTED', 'The squad is full. We’ll notify you if a spot opens up.'] : ['PAYMENT NEEDS ATTENTION', registration.payment?.rejection_reason || 'Please submit a new payment screenshot.'];
  const share = async () => { if (navigator.share) await navigator.share({ title: match.name, url: window.location.href }); else { await navigator.clipboard?.writeText(window.location.href); toast('Match link copied'); } };
  const calendar = () => { const start = `${match.date.replaceAll('-', '')}T${match.start_time.replaceAll(':', '')}00`; const end = `${match.date.replaceAll('-', '')}T${match.end_time.replaceAll(':', '')}00`; const file = new Blob([`BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nDTSTART;TZID=Asia/Kolkata:${start}\nDTEND;TZID=Asia/Kolkata:${end}\nSUMMARY:${match.name}\nLOCATION:${match.venue}\nEND:VEVENT\nEND:VCALENDAR`], { type: 'text/calendar' }); const a = document.createElement('a'); a.href = URL.createObjectURL(file); a.download = 'stranger-club-match.ics'; a.click(); };
  return <section className="status-page"><button className="back" onClick={back}><ArrowLeft /> MATCH DETAILS</button><div className={cn('status-icon', confirmed && 'success', rejected && 'danger')}><CheckCircle2 /></div><p className="eyebrow">{dateText(match.date)}</p><h1>{content[0]}</h1><p>{content[1]}</p><div className="ticket"><div><b>{match.name}</b><span>{timeText(match.start_time)} · {match.venue}</span></div><Status status={playerStatus(registration)} /><footer><small>PAYMENT</small><strong>{confirmed ? `₹${registration.payment?.amount}` : submitted ? 'VERIFYING' : waitlisted ? 'WAITLISTED' : 'REUPLOAD'}</strong></footer></div>{confirmed && <button className="primary-button" onClick={calendar}><CalendarPlus /> ADD TO CALENDAR</button>}{submitted && <button className="primary-button" onClick={refresh}>REFRESH STATUS</button>}{rejected && <button className="primary-button" onClick={retry}>UPLOAD NEW PROOF</button>}<button className="ghost-button" onClick={share}><Share2 /> SHARE MATCH</button></section>;
}

function AdminLogin() {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const auth = await api('/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username, password }) }); csrfToken = auth.csrf_token; window.location.assign('/admin'); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <main className="login-page"><Brand /><section><p className="eyebrow">ORGANIZER ACCESS</p><h1>WELCOME BACK.</h1><p>Sign in to manage events and payments.</p><form className="form" onSubmit={submit}><Field label="USERNAME" value={username} set={setUsername} autoComplete="username" required /><Field label="PASSWORD" type="password" value={password} set={setPassword} autoComplete="current-password" required /><FormError>{error}</FormError><button className="primary-button" disabled={busy}>{busy ? <LoaderCircle className="spin" /> : 'SIGN IN'}<ChevronRight /></button></form></section></main>;
}

function Admin() {
  const [matches, setMatches] = useState(); const [view, setView] = useState('dashboard'); const [selected, setSelected] = useState(); const [error, setError] = useState(''); const [toast, setToast] = useState('');
  const load = async () => { try { const auth = await api('/auth/me'); csrfToken = auth.csrf_token; setMatches(await api('/admin/events')); } catch (err) { if (err.message === 'Authentication required') window.location.assign('/admin/login'); else setError(err.message); } }; useEffect(() => { load(); }, []);
  const choose = async (id) => { try { setSelected(await api(`/admin/matches/${id}`)); setView('manage'); } catch (err) { setError(err.message); } };
  if (error) return <ErrorPage message={error} />; if (!matches) return <Loading />;
  return <main className="admin"><Toast text={toast} clear={() => setToast('')} /><header className="admin-header"><Brand /><span><a href={`/m/${DEFAULT_MATCH}`}>PUBLIC SITE <ArrowUpRight size={14} /></a><button className="logout" onClick={async () => { await api('/auth/logout', { method: 'POST' }); csrfToken = ''; window.location.assign('/admin/login'); }}>LOG OUT</button></span></header>{view === 'dashboard' && <Dashboard matches={matches} choose={choose} create={() => setView('create')} />}{view === 'create' && <Create back={() => setView('dashboard')} created={async (item) => { await load(); await choose(item.id); setToast('Match is live and ready to share'); }} />}{view === 'manage' && <Manage match={selected} back={() => setView('dashboard')} refresh={() => choose(selected.id)} toast={setToast} />}</main>;
}

function Dashboard({ matches, choose, create }) {
  const total = matches.reduce((a, m) => ({ pending: a.pending + m.payment_submitted_count, confirmed: a.confirmed + m.confirmed_count, waitlist: a.waitlist + m.waitlist_count, revenue: a.revenue + m.collected_amount }), { pending: 0, confirmed: 0, waitlist: 0, revenue: 0 }); const now = new Date(); const upcoming = matches.filter((item) => new Date(`${item.date}T${item.start_time}`) >= now && !['COMPLETED', 'CANCELLED'].includes(item.status)); const historical = matches.filter((item) => !upcoming.includes(item));
  const EventRows = ({ items, empty }) => items.length ? items.map((match) => <button className="match-row" key={match.id} onClick={() => choose(match.id)}><span><small>{dateText(match.date)} · {match.status}</small><b>{match.name}</b><i>{match.venue} · {timeText(match.start_time)} · {match.payment_submitted_count} TO REVIEW</i></span><strong>{match.confirmed_count}<i>/{match.capacity}</i><small>PLAYERS</small></strong><ChevronRight /></button>) : <div className="empty"><Users /><h2>{empty}</h2><p>Create an event when the next game is confirmed.</p></div>;
  return <><section className="admin-hero"><p className="eyebrow lime">ORGANIZER HQ</p><h1>THIS WEEK’S<br />PLAYBOOK.</h1><p>Everything that needs your attention, in one place.</p></section><section className="admin-body"><div className="ops"><Stat text="TO REVIEW" value={total.pending} color="orange" /><Stat text="CONFIRMED" value={total.confirmed} color="green" /><Stat text="WAITLIST" value={total.waitlist} color="blue" /><Stat text="COLLECTED" value={`₹${total.revenue}`} color="black" /></div><div className="section-title"><div><p className="eyebrow">UPCOMING</p><h2>EVENTS</h2></div><button className="round-button" onClick={create}><Plus /></button></div><EventRows items={upcoming} empty="NO UPCOMING EVENTS" />{historical.length > 0 && <><div className="section-title"><div><p className="eyebrow">HISTORY</p><h2>PAST EVENTS</h2></div></div><EventRows items={historical} empty="NO PAST EVENTS" /></>}</section></>;
}
function Stat({ text, value, color }) { return <div className={cn('stat', color)}><small>{text}</small><b>{value}</b></div>; }

function Manage({ match, back, refresh, toast }) {
  const [proof, setProof] = useState(); const [reject, setReject] = useState(); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false); const pending = match.registrations.filter((p) => p.payment?.status === 'SUBMITTED'); const waitlist = match.registrations.filter((p) => p.status === 'WAITLISTED');
  const link = `${window.location.origin}/m/${match.public_id}`; const copy = async () => { await navigator.clipboard?.writeText(link); toast('Public match link copied'); }; const share = async () => { if (navigator.share) await navigator.share({ title: match.name, url: link }); else copy(); };
  const review = async (id, allow) => { setBusy(true); try { await api(`/admin/payments/${id}/${allow ? 'confirm' : 'reject'}`, { method: 'POST', headers: allow ? undefined : { 'Content-Type': 'application/json' }, body: allow ? undefined : JSON.stringify({ reason }) }); setProof(); setReject(); await refresh(); toast(allow ? 'Payment confirmed' : 'Payment rejected'); } catch (err) { toast(err.message); } finally { setBusy(false); } };
  const promote = async (id) => { try { await api(`/admin/registrations/${id}/promote`, { method: 'POST' }); await refresh(); toast('Player moved off the waitlist'); } catch (err) { toast(err.message); } };
  return <section className="manage"><button className="back" onClick={back}><ArrowLeft /> ALL MATCHES</button><div className="manage-top"><div><p className="eyebrow">{dateText(match.date)} · {timeText(match.start_time)}</p><h1>{match.name}</h1><span><MapPin />{match.venue}</span></div><Status status="CONFIRMED" /></div><div className="metrics"><div><b>{match.confirmed_count}<i>/{match.capacity}</i></b><small>CONFIRMED</small></div><div><b>{match.pending_count}</b><small>TO REVIEW</small></div><div><b>{match.waitlist_count}</b><small>WAITLISTED</small></div></div><div className="share-buttons"><button onClick={copy}><Copy /> COPY LINK</button><button onClick={share}><Share2 /> SHARE</button></div><List title={`PAYMENTS TO REVIEW · ${pending.length}`}>{pending.length ? pending.map((p) => <button className="review" key={p.id} onClick={() => setProof(p)}><span className="avatar">{p.name[0]}</span><span><b>{p.name}</b><small>₹{p.payment.amount} · submitted {new Intl.DateTimeFormat('en-IN', { hour: 'numeric', minute: '2-digit' }).format(new Date(p.payment.submitted_at))}</small></span><i><ImagePlus /> VIEW</i></button>) : <p className="quiet">Nothing waiting for you. Nice.</p>}</List><List title={`SQUAD · ${match.registrations.length}`}>{match.registrations.filter((p) => p.status !== 'WAITLISTED').map((p) => <PlayerRow key={p.id} item={p} open={() => p.payment && setProof(p)} />)}</List>{waitlist.length > 0 && <List title={`WAITLIST · ${waitlist.length}`}>{waitlist.map((p) => <PlayerRow key={p.id} item={p} action="PROMOTE" act={() => promote(p.id)} />)}</List>}{proof && <Proof player={proof} close={() => setProof()} confirm={() => review(proof.payment.id, true)} reject={() => { setProof(); setReject(proof); }} busy={busy} />}{reject && <Reject reason={reason} setReason={setReason} close={() => setReject()} submit={() => review(reject.payment.id, false)} busy={busy} />}</section>;
}
function List({ title, children }) { return <section className="list"><h2>{title}</h2><div>{children}</div></section>; }
function PlayerRow({ item, open, action, act }) { return <div className="player-row"><span className="avatar">{item.name[0]}</span><span><b>{item.name}</b><small>{item.phone} · {item.preferred_position.replaceAll('_', ' ')}</small></span><Status status={playerStatus(item)} />{action && <button onClick={act}>{action}</button>}{open && <button onClick={open}><ArrowUpRight size={17} /></button>}</div>; }

function Create({ back, created }) {
  const [form, setForm] = useState({ name: 'Sunday Cricket', date: '2026-08-30', start_time: '07:00', end_time: '10:00', venue: 'PlayArena, Bellandur', capacity: '22', fee: '300', registration_deadline: '2026-08-29T20:00', upi_id: 'strangerclub@upi' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const update = (k) => (v) => setForm({ ...form, [k]: v });
  const submit = async (e) => { e.preventDefault(); setBusy(true); try { created(await api('/admin/matches', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, capacity: +form.capacity, fee: +form.fee, registration_deadline: `${form.registration_deadline}:00` }) })); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <section className="create"><button className="back" onClick={back}><ArrowLeft /> DASHBOARD</button><div className="intro"><p className="eyebrow">NEW GAME</p><h1>SET THE STAGE.</h1><p>Make the next match shareable in a minute.</p></div><form className="form admin-form" onSubmit={submit}><Field label="MATCH NAME" value={form.name} set={update('name')} required /><div className="pair"><Field label="DATE" type="date" value={form.date} set={update('date')} required /><Field label="CAPACITY" type="number" min="2" value={form.capacity} set={update('capacity')} required /></div><div className="pair"><Field label="START" type="time" value={form.start_time} set={update('start_time')} required /><Field label="END" type="time" value={form.end_time} set={update('end_time')} required /></div><Field label="VENUE" value={form.venue} set={update('venue')} required /><div className="pair"><Field label="FEE (₹)" type="number" min="1" value={form.fee} set={update('fee')} required /><Field label="UPI ID" value={form.upi_id} set={update('upi_id')} required /></div><Field label="REGISTRATION CLOSES" type="datetime-local" value={form.registration_deadline} set={update('registration_deadline')} required /><FormError>{error}</FormError><button className="primary-button" disabled={busy}>{busy ? <LoaderCircle className="spin" /> : 'CREATE & GET LINK'}<ChevronRight /></button></form></section>;
}
function Proof({ player, close, confirm, reject, busy }) { return <div className="overlay"><section className="sheet"><button className="close" onClick={close}><X /></button><p className="eyebrow">PAYMENT REVIEW</p><h2>{player.name}</h2><strong className="amount">₹{player.payment.amount}</strong><img src={player.payment.screenshot_url} alt="Payment proof" /><p className="quiet">Submitted {new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(player.payment.submitted_at))}</p><div className="review-actions"><button className="ghost-button" onClick={reject} disabled={busy}>REJECT</button><button className="primary-button" onClick={confirm} disabled={busy}>{busy ? <LoaderCircle className="spin" /> : 'CONFIRM PAYMENT'}<Check /></button></div></section></div>; }
function Reject({ reason, setReason, close, submit, busy }) { return <div className="overlay"><section className="sheet reject"><button className="close" onClick={close}><X /></button><p className="eyebrow">REJECT PAYMENT</p><h2>WHAT NEEDS FIXING?</h2><p className="quiet">This note is shown to the player so they can submit a new proof.</p><textarea value={reason} onChange={(e) => setReason(e.target.value)} placeholder="e.g. The transaction reference is not visible." autoFocus /><button className="primary-button" disabled={busy || reason.trim().length < 3} onClick={submit}>{busy ? <LoaderCircle className="spin" /> : 'REJECT PAYMENT'}</button></section></div>; }
